VentureWeb/Controllers/CompanyController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using VentureWeb.DAL;
using VentureWeb.Models;

namespace VentureWeb.Controllers
{
    public class CompanyController : Controller
    {
        private readonly ILogger<CompanyController> _logger;
        private readonly ICompanyaccess _companyaccess;
        public CompanyController(ILogger<CompanyController> logger, ICompanyaccess companyaccess)
        {
            _logger = logger;
            _companyaccess = companyaccess;
        }

        [HttpGet]
        public IActionResult AddEditCompany(string id)
        {
            if (String.IsNullOrEmpty(id))
            {
                TempData["Mode"] = "Add";
                return View();
            }
            else
            {
                TempData["Mode"] = "Edit";
                var company = _companyaccess.GetCompany(id);
                return View(company);
            }
        }

        [HttpPost]
        public IActionResult Company(Company model, bool add)
        {

            try
            {
                if (add)
                {
                    if (model.CompId == null)
                        throw new Exception("Enter Company Id.");
                    if (model.CompName == null)
                        throw new Exception("Enter Company Name.");
                    _companyaccess.AddCompany(model);
                    TempData["alertMessage"] = "company added Successfully";
                }
                else
                {
                    _companyaccess.EditCompany(model);

                    TempData["alertMessage"] = "Company Updated Successfully";
                }
            }
            catch (Exception ex)
            {
                throw ex;
            }
            return RedirectToAction("ListCompany");
        }

        [HttpGet]
        public IActionResult ListCompany()

        {
            try
            {
                var companyList = _companyaccess.CompanyList(1, 10);
                return View(companyList);
            }
            catch (Exception)
            {

                throw;
            }

        }


        [HttpGet]
        public IActionResult Delete(string id)
        {
            try
            {
                if (id != "")
                {

                    bool flag = _companyaccess.DeleteCompany(id);
                    TempData["alertMessage"] = "Deleted Successfully";

                }


            }
            catch (Exception ex)
            {

                throw ex;
            }

            //  return View(personalDetail);
            return RedirectToAction("ListCompany");
        }

    }
}

VentureWeb/Controllers/ProductRateController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using VentureWeb.DAL;
using VentureWeb.Models;

namespace VentureWeb.Controllers
{
    public class ProductRateController : Controller
    {
        private readonly ILogger<ProductRateController> _logger;
        private readonly IProductRateaccess _productrateaccess;
        public ProductRateController(ILogger<ProductRateController> logger, IProductRateaccess productrateaccess)
        {
            _logger = logger;
            _productrateaccess = productrateaccess;
        }

        [HttpGet]
        public IActionResult AddEditProductRate(string id)
        {
            if (String.IsNullOrEmpty(id))
            {
                TempData["Mode"] = "Add";
                return View();
            }
            else
            {
                TempData["Mode"] = "Edit";
                var productrate = _productrateaccess.GetProductRate(id);
                return View(productrate);
            }
        }

        [HttpPost]
        public IActionResult ProductRate(ProductRate model, bool add)
        {

            try
            {
                if (add)
                {
                    if (model.RateId == null)
                        throw new Exception("Enter ProductRate Id.");
                    if (model.Rate == null)
                        throw new Exception("Enter ProductRate Name.");
                    _productrateaccess.AddProductRate(model);
                    TempData["alertMessage"] = "ProductRate added Successfully";
                }
                else
                {
                    _productrateaccess.EditProductRate(model);

                    TempData["alertMessage"] = "ProductRate Updated Successfully";
                }
            }
            catch (Exception ex)
            {
                throw ex;
            }
            return RedirectToAction("ListProductRate");
        }

        [HttpGet]
        public IActionResult ListProductRate()
        {
            try
            {
                var productrateList = _productrateaccess.ProductRateList(1, 10);
                return View(productrateList);
            }
            catch (Exception)
            {

                throw;
            }

        }


        [HttpGet]
        public IActionResult Delete(string id)
        {
            try
            {
                if (id != "")
                {

                    bool flag = _productrateaccess.DeleteProductRate(id);
                    TempData["alertMessage"] = "Deleted Successfully";

                }


            }
            catch (Exception ex)
            {

                throw ex;
            }

            //  return View(personalDetail);
            return RedirectToAction("ListProductRate");
        }
    }
}

VentureWeb/Controllers/UnitController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using VentureWeb.DAL;
using VentureWeb.Models;

namespace VentureWeb.Controllers
{
    public class UnitController : Controller
    {
        private readonly ILogger<UnitController> _logger;
        private readonly IUnitaccess _unitaccess;
        public UnitController(ILogger<UnitController> logger, IUnitaccess unitaccess)
        {
            _logger = logger;
            _unitaccess = unitaccess;
        }

        [HttpGet]
        public IActionResult AddEditUnit(string id)
        {
            if (String.IsNullOrEmpty(id))
            {
                TempData["Mode"] = "Add";
                return View();
            }
            else
            {
                TempData["Mode"] = "Edit";
                var unit = _unitaccess.GetUnit(id);
                return View(unit);
            }
        }

        [HttpPost]
        public IActionResult Unit(Unit model, bool add)
        {

            try
            {
                model.EntryUserDate = DateTime.Now;
                model.UpdateUserDate = DateTime.Now;
                model.EntryUserId = Convert.ToInt32(HttpContext.Session.Keys.Select(x => x == "userId").FirstOrDefault());

                if (add)
                {
                    if (model.UnitId == null)
                        throw new Exception("Enter Unit Id.");
                    if (model.UnitName == null)
                        throw new Exception("Enter Unit Name.");
                    _unitaccess.AddUnit(model);
                    TempData["alertMessage"] = "unit added Successfully";
                }
                else
                {
                    _unitaccess.EditUnit(model);

                    TempData["alertMessage"] = "Unit Updated Successfully";
                }
            }
            catch (Exception ex)
            {
                throw ex;
            }
            return RedirectToAction("ListUnit");
        }

        [HttpGet]
        public IActionResult ListUnit()

        {
            try
            {
                var unitList = _unitaccess.UnitList(1, 10);
                return View(unitList);
            }
            catch (Exception)
            {

                throw;
            }

        }


        [HttpGet]
        public IActionResult Delete(string id)
        {
            try
            {
                if (id != "")
                {

                    bool flag = _unitaccess.DeleteUnit(id);
                    TempData["alertMessage"] = "Deleted Successfully";

                }


            }
            catch (Exception ex)
            {

                throw ex;
            }

            //  return View(personalDetail);
            return RedirectToAction("ListUnit");
        }

    }
}

VentureWeb/Controllers/UserController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using VentureWeb.DAL;
using VentureWeb.Models;
using VentureWeb.ViewModel;
using VentureWeb.Helpers;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Text;
using System.Web;
using System.Security.Cryptography;
using System.Diagnostics;
using Microsoft.AspNetCore.Http;
//using Microsoft.AspNetCore.Http;


namespace VentureWeb.Controllers
{
    public class UserController : Controller
    {
        private readonly ILogger<UserController> _logger;
        private readonly IUseraccess _useraccess;
        public UserController(ILogger<UserController> logger, IUseraccess useraccess)
        {
            _logger = logger;
            _useraccess = useraccess;
        }

        [HttpGet]
        public IActionResult Registration(string id)
        {    
            var UserViewModel = new UserViewModel();         
            if (String.IsNullOrEmpty(id))
            {
                var userStatus = Enum.GetValues(typeof(UserStatus)).Cast<UserStatus>().Select(v => new SelectListItem
                {
                    Text = v.ToString(),
                    Value = ((int)v).ToString()
                }).ToList();
                UserViewModel.UserState = userStatus;
                return View(UserViewModel);
            }
            else
            {
                var user = _useraccess.GetUser(id);
                var userStatus = Enum.GetValues(typeof(UserStatus)).Cast<UserStatus>().Select(v => new SelectListItem
                {
                    Text = v.ToString(),
                    Value = ((int)v).ToString()
                }).ToList();
                userStatus.First(x => x.Value == user.UserStatus.ToString()).Selected = true;
                UserViewModel.UserState = userStatus;               
               

                //  ViewBag.userStatus = userStatus;
                UserViewModel.Registration = user;
               //UserViewModel.UserState = userStatus;
                return View(UserViewModel);
            }
        }

        [HttpPost]
        public IActionResult Registration(Registration model,bool add)
        {

            try
            {
                if (add)
                {
                    if (model.EmpNo == null)
                        throw new Exception("Enter Employee Id.");
                    if (model.EmailId == null)
                        throw new Exception("Enter Email Id.");
                    _useraccess.AddUser(model);
                    TempData["alertMessage"] = "Registerd Successfully";
                }
                else
                {
                    _useraccess.EditUser(model);

                    TempData["alertMessage"] = "Updated Successfully";
                }
                //return RedirectToAction("ListUsers");
            }
            catch (Exception ex)
            {
                TempData["alertMessage"] = ex.Message.ToString();
                //  throw ex;
                //return View();
            }

            return RedirectToAction("ListUsers");
        }

        [HttpGet]
        public IActionResult ListUsers()

        {
            try
            {
                var userList = _useraccess.UserList(1, 10);
                return View(userList);
            }
            catch (Exception)
            {

                throw;
            }

        }

        [HttpGet]
        public IActionResult Delete(string id)
        {
            try
            {
                if (id != "")
                {
                    
                    bool flag = _useraccess.DeleteUser(id);
                    TempData["alertMessage"] = "Deleted Successfully";

                }
               
               
            }
            catch (Exception ex)
            {

                throw ex;
            }

            //  return View(personalDetail);
            return RedirectToAction("ListUsers");
        }

        [HttpGet]
        public IActionResult ResetPassword(string id)
        {
            if (String.IsNullOrEmpty(id))
            {

                return View();
            }
            else
            {
                ViewBag.EmpId = id;
                var user = _useraccess.GetUser(id);
                return View(user);
            }
        }

        [HttpPost]
        public ActionResult ResetPassword(Registration model)
        {            
            try
            {
                bool resetResponse = _useraccess.ResetPassword(model.EmpNo, model.Password);
                if (resetResponse)
                {
                    TempData["alertMessage"] = "Successfully Changed";
                }
                else
                {
                    TempData["alertMessage"] = "Something went horribly wrong!";
                }
            }
            catch (Exception ex)
            {
                throw ex;
            }
            return View();
           
        }

        [HttpGet]
        public IActionResult UserRegistration()
        {
            return View();           
        }

        [HttpPost]
        public IActionResult UserRegistration(Registration model, bool add)
        {
            try
            {
                if (add)
                {
                    if (model.EmpNo == null)
                        throw new Exception("Enter Employee Id.");
                    if (model.EmailId == null)
                        throw new Exception("Enter Email Id.");
                    _useraccess.AddUser(model);
                    TempData["alertMessage"] = "Registerd Successfully";
                }
                else
                {
                    _useraccess.EditUser(model);
                    TempData["alertMessage"] = "Updated Successfully";
                }
                //return RedirectToAction("ListUsers");
            }
            catch (Exception ex)
            {
                TempData["alertMessage"] = ex.Message.ToString();
                //  throw ex;               
            }
            return RedirectToAction("ListUsers");
        }


        public IActionResult UserLogin()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Login(string username, string password)
        {
            var data = _useraccess.GetUserByEmailIdandPassword(username, password);
            if (data.Count() > 0)
            {
                HttpContext.Session.SetString("username", data.FirstOrDefault().Name);
                HttpContext.Session.SetString("userId", data.FirstOrDefault().EmpNo);


                return RedirectToAction("Home", "Home");
            }
           
            else
            {
                ViewBag.error = "Invalid Account";
                return View("UserLogin");
            }
        }

        [HttpGet]
        public IActionResult Logout()
        {
            HttpContext.Session.Remove("username");
            return RedirectToAction("UserLogin");
        }


    }
}

VentureWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - VentureWeb</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.0/jquery.validate.min.js"></script>  
    <script src="Scripts/jquery-1.4.1.min.js" type="text/javascript"></script>
    <link href="~/css/nivo-slider.css" rel="stylesheet" type="text/css" />
    
</head>
<body>
    <header>
        <nav class="navbar navbar-light bg-info navbar-expand-sm sticky-top">
            <div class="container">
                <a class="navbar-brand text-white" asp-area="" asp-controller="Home" asp-action="Index">VentureWeb</a>
                <button class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarCollapse">
                    <ul class="navbar-nav ml-auto">
                        <li clas="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Home">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="User" asp-action="ListUsers">Users</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Company" asp-action="ListCompany">Company</a>
                        </li>
                        @*<li class="nav-item">
            <a class="nav-link text-white" asp-area="" asp-controller="ProductCategory" asp-action="ListProductCategory">Product Categories</a>
        </li>*@
                        <li class="nav-item dropdown">
                            <a class="nav-link text-white dropdown-toggle" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Product
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                <a class="dropdown-item" asp-area="" asp-controller="Product" asp-action="ProductList">Product List</a>
                                <a class="dropdown-item" asp-area="" asp-controller="ProductCategory" asp-action="ListProductCategory">Product Categories</a>
                                <a class="dropdown-item" asp-area="" asp-controller="ProductClass" asp-action="ListProductClass">Product Class</a>
                                <a class="dropdown-item" asp-area="" asp-controller="Unit" asp-action="ListUnit">Unit</a>
                                @*<a class="dropdown-item" asp-area="" asp-controller="Product" asp-action="ListProductsByCategory">ListProductsByCategory</a><a class="dropdown-item" asp-area="" asp-controller="ProductRate" asp-action="ListProductRate"></a>*@


                            </div>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link text-white dropdown-toggle" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Accounts
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                <a class="dropdown-item" asp-area="" asp-controller="Ledger" asp-action="ListLedgerGroup">LedgerGroup List</a>
                                <a class="dropdown-item" asp-area="" asp-controller="Ledger" asp-action="ListLedgerName">LedgerName List</a>
                                <a class="dropdown-item" asp-area="" asp-controller="Ledger" asp-action="ListSubLedgerClass">Sub Ledger Class List</a>
                                @*<a class="dropdown-item" asp-area="" asp-controller="Unit" asp-action="ListUnit">Unit</a>*@
                                @*<a class="dropdown-item" asp-area="" asp-controller="Product" asp-action="ListProductsByCategory">ListProductsByCategory</a><a class="dropdown-item" asp-area="" asp-controller="ProductRate" asp-action="ListProductRate"></a>*@


                            </div>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-controller="User" asp-action="logout">Logout</a>


                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="mb-5 pb-5">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            <div class="row">
                <div class="col-md-12 text-center">
                    <p>&copy; 2021 | VentureWeb</p>
                </div>
            </div>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>