VentureWeb/Controllers/LedgerController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using VentureWeb.DAL;
using VentureWeb.Models;
using VentureWeb.ViewModel;

namespace VentureWeb.Controllers
{
    public class LedgerController : Controller
    {
        private readonly ILogger<LedgerController> _logger;
        private readonly ILedgerAccess _ledgeraccess;
        public LedgerController(ILogger<LedgerController> logger, ILedgerAccess ledgeraccess)
        {
            _logger = logger;
            _ledgeraccess = ledgeraccess;
        }

        #region LedgerGroup
        


        [HttpGet]
        public IActionResult AddEditLedgerGroup(long id,long underid)
        {
            try
            {
                if (id==0)
                {
                    TempData["Mode"] = "Add";
                    var ledgergroup = _ledgeraccess.GetParentLedgerGroup(underid);
                    var addledgervm = new LedgerGroupVM();
                    addledgervm.ParentGroupName = ledgergroup.LedgerGroupName;
                    addledgervm.UnderId = ledgergroup.LedgerGroupId;
                    return View(addledgervm);
                }
                else
                {
                    TempData["Mode"] = "Edit";
                    var ledgergroup = _ledgeraccess.GetLedgerGroup(id);
                    return View(ledgergroup);
                }
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        [HttpPost]
        public IActionResult LedgerGroup(LedgerGroup model, bool add)
        {

            try
            {
                model.EntryUserDate = DateTime.Now;
                model.UpdateUserDate = DateTime.Now;
                model.EntryUserId = Convert.ToInt32(HttpContext.Session.Keys.Select(x => x == "userId").FirstOrDefault());
                model.CompId = 1;
                if (add)
                {
                    if (model.LedgerGroupId == null)
                        throw new Exception("Enter LedgerGroup Id.");
                    if (model.LedgerGroupName == null)
                        throw new Exception("Enter LedgerGroup Name.");
                    
                    _ledgeraccess.AddLedgerGroup(model);
                    TempData["alertMessage"] = "ledgergroup added Successfully";
                }
                else
                {
                    //model.EntryUserDate = DateTime.Now;
                    //model.UpdateUserDate = DateTime.Now;
                    _ledgeraccess.EditLedgerGroup(model);
                    TempData["alertMessage"] = "LedgerGroup Updated Successfully";
                }
            }
            catch (Exception ex)
            {
                throw ex;
            }
            return RedirectToAction("ListLedgerGroup");
        }

        [HttpGet]
        public IActionResult ListLedgerGroup()
        {
            try
            {
                var ledgergroupList = _ledgeraccess.LedgerGroupList(1, 10);
                return View(ledgergroupList);
            }
            catch (Exception)
            {

                throw;
            }

        }

        [HttpGet]
        public IActionResult Delete(long id)
        {
            try
            {
                if (id != 0)
                {

                    bool flag = _ledgeraccess.DeleteLedgerGroup(id);
                    TempData["alertMessage"] = "Deleted Successfully";

                }


            }
            catch (Exception ex)
            {

                throw ex;
            }
                        
            return RedirectToAction("ListLedgerGroup");
        }


        #endregion LedgerGroup


        #region LedgerName

        [HttpGet]
        public IActionResult AddEditLedgerName(long id)
        {
            try
            {
                var AddEditLedgerNameVM = new AddEditLedgerNameVM();
                AddEditLedgerNameVM.LedgerGroup = _ledgeraccess.LedgerGroupList(1,20);
                if (id==0)
                {
                    TempData["Mode"] = "Add";
                    return View(AddEditLedgerNameVM);
                }
                else
                {
                    TempData["Mode"] = "Edit";
                    AddEditLedgerNameVM.Ledger = _ledgeraccess.GetLedgerDetails(id);
                    return View(AddEditLedgerNameVM);
                }
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        [HttpPost]
        public IActionResult LedgerName(Ledger model, bool add)
        {

            try
            {
                model.EntryUserDate = DateTime.Now;
                model.UpdateUserDate = DateTime.Now;
                model.EntryUserId = Convert.ToInt32(HttpContext.Session.Keys.Select(x => x == "userId").FirstOrDefault());
                model.CompId = 1;
                if (add)
                {
                    if (model.LedgerId == null)
                        throw new Exception("Enter Ledger Id.");
                    if (model.LedgerName == null)
                        throw new Exception("Enter Ledger Name.");
                    _ledgeraccess.AddLedgerName(model);
                    TempData["alertMessage"] = "ledgername added Successfully";
                }
                else
                {
                    _ledgeraccess.EditLedgerName(model);

                    TempData["alertMessage"] = "LedgerName Updated Successfully";
                }
            }
            catch (Exception ex)
            {
                throw ex;
            }
            return RedirectToAction("ListLedgerName");
        }

        [HttpGet]
        public IActionResult ListLedgerName()
        {
            try
            {
                var ledgernameList = _ledgeraccess.LedgerNameList(1, 10);
                return View(ledgernameList);
            }
            catch (Exception)
            {

                throw;
            }

        }

        [HttpGet]
        public IActionResult DeleteLedgerName(long id)
        {
            try
            {
                if (id != 0)
                {

                    bool flag = _ledgeraccess.DeleteLedgerName(id);
                    TempData["alertMessage"] = "Deleted Successfully";

                }


            }
            catch (Exception ex)
            {

                throw ex;
            }

            
            return RedirectToAction("ListLedgerName");
        }


        #endregion LedgerName

        #region SubLedgerClass

        [HttpGet]
        public IActionResult AddEditSubLedgerClass(long id, long underid)
        {
            try
            {
                if (id == 0)
                {
                    TempData["Mode"] = "Add";
                    var subledgerclass = _ledgeraccess.GetParentSubLedgerClass(underid);
                    var addsubledgerclassvm = new SubLedgerClassVM();
                    addsubledgerclassvm.ParentClassName = subledgerclass.SubLedgerClassName;
                    addsubledgerclassvm.UnderId = subledgerclass.SubLedgerClassId;
                    return View(addsubledgerclassvm);
                }
                else
                {
                    TempData["Mode"] = "Edit";
                    var addsubledgerclassvm = _ledgeraccess.GetParentSubLedgerClass(id);
                    return View(addsubledgerclassvm);
                }
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        [HttpPost]
        public IActionResult SubLedgerClass(SubLedgerClass model, bool add)
        {

            try
            {
                model.EntryUserDate = DateTime.Now;
                model.UpdateUserDate = DateTime.Now;
                model.EntryUserId = Convert.ToInt32(HttpContext.Session.Keys.Select(x => x == "userId").FirstOrDefault());
                model.CompId = 1;
                if (add)
                {
                    if (model.SubLedgerClassId == null)
                        throw new Exception("Enter SubLedgerClass Id.");
                    if (model.SubLedgerClassName == null)
                        throw new Exception("Enter SubLedgerClass Name.");

                    _ledgeraccess.AddSubLedgerClass(model);
                    TempData["alertMessage"] = "subledgerclass added Successfully";
                }
                else
                {
                    //model.EntryUserDate = DateTime.Now;
                    //model.UpdateUserDate = DateTime.Now;
                    _ledgeraccess.EditSubLedgerClass(model);
                    TempData["alertMessage"] = "SubLedgerClass Updated Successfully";
                }
            }
            catch (Exception ex)
            {
                throw ex;
            }
            return RedirectToAction("ListSubLedgerClass");
        }

        [HttpGet]
        public IActionResult ListSubLedgerClass()
        {
            try
            {
                var subledgerclassList = _ledgeraccess.SubLedgerClassList(1, 10);
                return View(subledgerclassList);
            }
            catch (Exception)
            {

                throw;
            }

        }

        [HttpGet]
        public IActionResult DeleteSubLedgerClass(long id)
        {
            try
            {
                if (id != 0)
                {

                    bool flag = _ledgeraccess.DeleteSubLedgerClass(id);
                    TempData["alertMessage"] = "Deleted Successfully";

                }


            }
            catch (Exception ex)
            {

                throw ex;
            }

            return RedirectToAction("ListSubLedgerClass");
        }

        #endregion SubLedgerClass

    }
}

VentureWeb/Views/Ledger/AddEditLedgerGroup.cshtml
@model VentureWeb.ViewModel.LedgerGroupVM


@{
    ViewData["Title"] = "LedgerGroup";

}

<div>
    <div class="top-bar mt-3">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a asp-area="" asp-controller="Home" asp-action="Home">Home</a></li>
                <li class="breadcrumb-item"><a asp-area="" asp-controller="Ledger" asp-action="ListLedgerGroup">LedgerGroup List</a></li>
                <li class="breadcrumb-item active" aria-current="page">@TempData["Mode"] LedgerGroup</li>
            </ol>
        </nav>
    </div>

    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <div class="row">
                        <div class="col-md-12">
                            <h5 class="my-1 card-title">Ledger Group Form</h5>
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    <form action="/Ledger/LedgerGroup?add=@(Model.LedgerGroupId==0)" class="form-horizontal" method="post">
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="">Ledger Group<span style="color:red;">*</span> :</label>
                                    <input type="hidden" value='@(Model==null?"":Model.LedgerGroupId.ToString())' name="LedgerGroupId" required />
                                    <input type="hidden" value='@(Model==null?"":Model.UnderId.ToString())' name="UnderId" required />
                                    <input type="text" class="form-control" value='@(Model==null?"":Model.LedgerGroupName)' name="LedgerGroupName" maxlength="50" required />
                                    <span class="field-validation-valid text-danger"
                                          data-valmsg-for="LedgerGroupName"
                                          data-valmsg-replace="true">
                                    </span>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="">Under :</label>
                                    <input type="text" disabled class="form-control" value='@(Model==null?"":Model.ParentGroupName)' name="ParentGroupName" required />
                                    <span class="field-validation-valid text-danger"
                                          data-valmsg-for="ParentString"
                                          data-valmsg-replace="true">
                                    </span>
                                </div>
                            </div>
                            @*<div class="col-md-6">
                                <div class="form-group">
                                    <label for="">IsParent<span style="color:red;">*</span> :</label>
                                    <input type="text" class="form-control" value='@(Model==null?"":Model.IsParent.ToString())' name="IsParent" required />
                                    <span class="field-validation-valid text-danger"
                                          data-valmsg-for="IsParent"
                                          data-valmsg-replace="true">
                                    </span>
                                </div>
                            </div>*@
                            @*<div class="col-md-6">
                                <div class="form-group">
                                    <label for="">ParentString<span style="color:red;">*</span> :</label>
                                    <input type="text" class="form-control" value='@(Model==null?"":Model.Parentstring)' name="Parentstring" required />
                                    <span class="field-validation-valid text-danger"
                                          data-valmsg-for="ParentString"
                                          data-valmsg-replace="true">
                                    </span>
                                </div>
                            </div>*@
                            @*<div class="col-md-6">
                                <div class="form-group">
                                    <label for="">IsMain<span style="color:red;">*</span> :</label>
                                    <input type="text" class="form-control" value='@(Model==null?"":Model.IsMain.ToString())' name="IsMain" required />
                                    <span class="field-validation-valid text-danger"
                                          data-valmsg-for="IsMain"
                                          data-valmsg-replace="true">
                                    </span>
                                </div>
                            </div>*@
                          
                        </div>
                        <div class="row justify-content-center">
                            <div class="col-md-6">
                                <div class="form-group mb-0">
                                    <input type="submit" class="btn btn-primary btn-sm btn-block" value="Save" name="save" />
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

VentureWeb/Views/Ledger/AddEditSubLedgerClass.cshtml
@model VentureWeb.ViewModel.SubLedgerClassVM


@{
    ViewData["Title"] = "SubLedgerClass";

}

<div>
    <div class="top-bar mt-3">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a asp-area="" asp-controller="Home" asp-action="Home">Home</a></li>
                <li class="breadcrumb-item"><a asp-area="" asp-controller="Ledger" asp-action="ListSubLedgerClass">SubLedgerClass List</a></li>
                <li class="breadcrumb-item active" aria-current="page">@TempData["Mode"] SubLedgerClass</li>
            </ol>
        </nav>
    </div>

    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <div class="row">
                        <div class="col-md-12">
                            <h5 class="my-1 card-title">Ledger Group Form</h5>
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    <form action="/Ledger/SubLedgerClass?add=@(Model.SubLedgerClassId==0)" class="form-horizontal" method="post">
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="">Ledger Group<span style="color:red;">*</span> :</label>
                                    <input type="hidden" value='@(Model==null?"":Model.SubLedgerClassId.ToString())' name="SubLedgerClassId" required />
                                    <input type="hidden" value='@(Model==null?"":Model.UnderId.ToString())' name="UnderId" required />
                                    <input type="text" class="form-control" value='@(Model==null?"":Model.SubLedgerClassName)' name="SubLedgerClassName" maxlength="50" required />
                                    <span class="field-validation-valid text-danger"
                                          data-valmsg-for="SubLedgerClassName"
                                          data-valmsg-replace="true">
                                    </span>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="">Under :</label>
                                    <input type="text" disabled class="form-control" value='@(Model==null?"":Model.ParentClassName)' name="ParentGroupName" required />
                                    <span class="field-validation-valid text-danger"
                                          data-valmsg-for="ParentString"
                                          data-valmsg-replace="true">
                                    </span>
                                </div>
                            </div>
                          

                        </div>
                        <div class="row justify-content-center">
                            <div class="col-md-6">
                                <div class="form-group mb-0">
                                    <input type="submit" class="btn btn-primary btn-sm btn-block" value="Save" name="save" />
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

VentureWeb/Views/Ledger/ListLedgerGroup.cshtml
@model List<VentureWeb.Models.LedgerGroup>

@{
    ViewData["Title"] = "ListLedgerGroup";
}
<style>
    ul, #myUL {
        list-style-type: none;
    }

    #myUL {
        margin: 0;
        padding: 0;
    }

    .caret {
        cursor: pointer;
        -webkit-user-select: none; /* Safari 3.1+ */
        -moz-user-select: none; /* Firefox 2+ */
        -ms-user-select: none; /* IE 10+ */
        user-select: none;
    }

        .caret::before {
            content: "\25B6";
            color: black;
            display: inline-block;
            margin-right: 6px;
        }

    .caret-down::before {
        -ms-transform: rotate(90deg); /* IE 9 */
        -webkit-transform: rotate(90deg); /* Safari */
        ' transform: rotate(90deg);
    }

    .nested {
        display: none;
    }

    .active {
        display: block;
    }
</style>


<div>
    <div class="top-bar mt-3">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a asp-area="" asp-controller="Home" asp-action="Home">Home</a></li>
                <li class="breadcrumb-item active" aria-current="page">LedgerGroup List</li>
            </ol>
        </nav>
    </div>

    <div class="card">
        <div class="card-header">
            <div class="row">
                <div class="col-md-6">
                    @*<h5 class="my-1 card-title">Product Class List</h5>*@
                </div>
                <div class="col-md-6 text-right">
                    @*<a class="btn btn-primary btn-sm" href="/Ledger/AddEditLedgerGroup" role="button"><i class="fa fa-plus"></i> Add LedgerGroup</a>*@
                </div>
            </div>
        </div>
        <div class="card-body">
            @if (null != TempData["alertMessage"])
            {
                <div class="alert alert-warning" role="alert">
                    @TempData["alertMessage"]
                </div>
            }

        <table class="table table-bordered table-sm mb-0">
            <tr>
                @*<th>Ledger Group Id</th>*@
                <th>Ledger Group Name</th>
                @*<th>Action</th>*@
            </tr>
            <tr><td>
                    <ul id="myUL">

                        @foreach (var ledgergroup in Model)
                        {


                          

                            @if (ledgergroup.UnderId == 0)
                            {
                                var subgroups = Model.Where(c => c.UnderId == ledgergroup.LedgerGroupId).ToList();
                        <li>
                            <span class="caret">@ledgergroup.LedgerGroupName</span>
                            
                            @*<a href="/Ledger/AddEditLedgerGroup" class="btn btn-outline-warning btn-sm" role="button"><i class="fa fa-plus"></i></a>
                            <a href="/Ledger/AddEditLedgerGroup?id=@ledgergroup.LedgerGroupId" class="btn btn-outline-warning btn-sm" role="button"><i class="fa fa-pencil"></i></a>
                            <a href="" onclick="return confirm('Are you sure you want to delete?');" class="btn btn-outline-danger btn-sm" role="button"><i class="fa fa-trash-o"></i></a>*@


                            @if (subgroups.Count > 0)
                            {
                                <ul class="nested">
                                    @foreach (var subgroup in subgroups)
                                    {
                                        var semisubgroups = Model.Where(c => c.UnderId == subgroup.LedgerGroupId).ToList();
                                        <li>
                                            @*@subgroup.LedgerGroupName*@
                                            <span class="caret">@subgroup.LedgerGroupName</span>
                                            <a href="/Ledger/AddEditLedgerGroup?UnderId=@subgroup.LedgerGroupId" class="btn btn-outline-warning btn-sm" role="button"><i class="fa fa-plus"></i></a>
                                            <a href="/Ledger/Delete?id=@subgroup.LedgerGroupId" class="btn btn-outline-warning btn-sm" role="button"><i class="fa fa-pencil"></i></a>
                                            <a href="" onclick="return confirm('Are you sure you want to delete?');" class="btn btn-outline-danger btn-sm" role="button"><i class="fa fa-trash-o"></i></a>

                                            @if (semisubgroups.Count > 0)
                                            {
                                                <ul class="nested">
                                                    @foreach (var semisubgroup in semisubgroups)
                                                    {
                                                    <li>
                                                        @semisubgroup.LedgerGroupName
                                                        <a href="/Ledger/AddEditLedgerGroup?id=@semisubgroup.LedgerGroupId" class="btn btn-outline-warning btn-sm" role="button"><i class="fa fa-pencil"></i></a>
                                                        <a href="/Ledger/Delete?id=@semisubgroup.LedgerGroupId" onclick="return confirm('Are you sure you want to delete?');" class="btn btn-outline-danger btn-sm" role="button"><i class="fa fa-trash-o"></i></a>

                                                    </li>
                                                    }
                                                </ul>
                                            }
                                        </li>

                                    }
                                </ul>
                            }

                        </li>

                                    }

                               

                                @*<span class="caret">Beverages</span>
                <ul class="nested">
                    <li>Water</li>
                    <li>Coffee</li>
                    <li>
                        <span class="caret">Tea</span>
                        <ul class="nested">
                            <li>Black Tea</li>
                            <li>White Tea</li>
                            <li>
                                <span class="caret">Green Tea</span>
                                <ul class="nested">
                                    <li>Sencha</li>
                                    <li>Gyokuro</li>
                                    <li>Matcha</li>
                                    <li>Pi Lo Chun</li>
                                </ul>
                            </li>
                        </ul>
                    </li>
                </ul>*@

                            }


                        </ul>
                </td></tr>
            
        </table>
        </div>
    </div>
</div>

<script>
    var toggler = document.getElementsByClassName("caret");
    var i;

    for (i = 0; i < toggler.length; i++) {
        toggler[i].addEventListener("click", function () {
            this.parentElement.querySelector(".nested").classList.toggle("active");
            this.classList.toggle("caret-down");
        });
    }
</script>

VentureWeb/Views/Ledger/ListLedgerName.cshtml
@model List<VentureWeb.ViewModel.LedgerNameVM>

@{
    ViewData["Title"] = "ListLedgerName";
}

<div>
    <div class="top-bar mt-3">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                <li class="breadcrumb-item active" aria-current="page">LedgerName List</li>
            </ol>
        </nav>
    </div>

    <div class="card">
        <div class="card-header">
            <div class="row">
                <div class="col-md-6">
                    <h5 class="my-1 card-title">Ledger Name List</h5>
                </div>
                <div class="col-md-6 text-right">
                    <a class="btn btn-primary btn-sm" href="/Ledger/AddEditLedgerName" role="button"><i class="fa fa-plus"></i> Add LedgerName</a>
                </div>
            </div>
        </div>
        <div class="card-body">
            @if (null != TempData["alertMessage"])
            {
                <div class="alert alert-warning" role="alert">
                    @TempData["alertMessage"]
                </div>
            }

            <table class="table table-bordered table-sm mb-0">
                <tr>
                    <th>Ledger Id</th>
                    <th>Ledger Name</th>
                    @*<th>Ledger Group Name</th>*@
                    <th>Action</th>
                </tr>

                @foreach (var ledgername in Model)
                {
            <tr>
                <td>@ledgername.LedgerId</td>
                <td>@ledgername.LedgerName</td>
                <td>@ledgername.LedgerGroupName</td>

                <td>
                    <a href="/Ledger/AddEditLedgerName?id=@ledgername.LedgerId" class="btn btn-outline-warning btn-sm" role="button"><i class="fa fa-pencil"></i></a>
                    <a href="/Ledger/Delete?id=@ledgername.LedgerName" onclick="return confirm('Are you sure you want to delete?');" class="btn btn-outline-danger btn-sm" role="button"><i class="fa fa-trash-o"></i></a>
                </td>
            </tr>
                }
            </table>
        </div>
    </div>
</div>